countdown = input("how many seconds until launch?\n>")
oxygen_tanks = input("how many oxygen tanks do you have?\n>")
food_packs = input("how many food pack do you have?\n>")
water_packs = input("how many water packs do you have?\n>")
print("countdown:" +countdown)
print("oxygen tanks:" + oxygen_tanks)
print("food packs:" +food_packs)
print("water packs:" + water_packs)
oxygen_tanks= input("confirm number of oxygen tanks\n>")
print("countdown:" +countdown)
print("oxygen tanks:" + oxygen_tanks)
print("food packs:" +food_packs)
print("water packs:" + water_packs)